### PR TITLE
fix: rename setStakerStakerReward and remove _isStakerActive

### LINKED ISSUE #878: remove `_isStakerActive` for v1

### LINKED ISSUE #879: rename setStakerStakerReward to setStakerReward

### PR DESCRIPTION
**Pull request by yohanelly95**
- [x] Fixes #879 
- [x] Fixes #878

### CODE REVIEW

File: test/StakeManager.js [hunk 1]
```diff
@@ -1187,40 +1187,6 @@ describe('StakeManager', function () {
       await stakeManager.connect(signers[0]).unpause();
     });
 
-    it('Delegation should revert, if staker is inactive for more than grace period', async function () {
```
Comment (yohanelly95) [inline test/StakeManager.js:1190]: @SamAg19 removed this test, since we don't have `_isStakerActive` check anymore. Do we still need some level of testing for this?

Comment (SamAg19) [reply test/StakeManager.js:1236]: No i don't think so it necessary

**Review by SamAg19 — APPROVED** [review]

File: test/StakeManager.js (hunk 1 above)
Comment (yohanelly95) [reply test/StakeManager.js:1236]: Resolved

**Review by rajkharvar — APPROVED** [review]
