### PR TITLE
fix: transfer razor only during testnet deployment

### LINKED ISSUE #818: [Post Deployment Script] Only transfer tokens in testnets: make the network check explicit
In https://github.com/razor-network/contracts/blob/master/migrations/src/postDeploymentSetup.js#L36, we need to be explicit in mentioning the network as "testnet" instead of !== "mainnet".

This needs to be done in v1 as well.

### PR DESCRIPTION
**Pull request by rajkharvar**
fixes #818

### CODE REVIEW

File: migrations/src/postDeploymentSetup.js [hunk 1]
```diff
@@ -76,7 +76,7 @@ module.exports = async () => {
   const stakerAddressList = STAKER_ADDRESSES.split(',');
 
   // Only transfer tokens in testnets
-  if (NETWORK !== 'mainnet') {
+  if (NETWORK === 'testnet') {
```
Comment (yohanelly95) [inline migrations/src/postDeploymentSetup.js:79]: Do we need to define the testnet networks explicitly here?

Comment (SkandaBhat) [reply migrations/src/postDeploymentSetup.js:79]: Introduce a new env variable, NETWORK_TYPE. Use that here. It will be either "MAINNET" or "TESTNET".

**Review by yohanelly95 — APPROVED** [review]
+1
